### ISSUE TITLE
DeprecationWarning: Custom PerformanceEntry accessors are deprecated

### ISSUE THREAD

**Issue by Olexandrio** [MGorkov/node-sysstat#3]
Error on Linux, node v18 (probably v16+) 
```
(node:545335) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
    at /.../node-sysstat/index.js:27:16
    at Array.map (<anonymous>)
    at PerformanceObserver.<anonymous> (/.../node-sysstat/index.js:27:10)
    at [kDispatch] (node:internal/perf/observe:322:19)
    at Immediate.<anonymous> (node:internal/perf/observe:126:25)
    at process.processImmediate (node:internal/timers:476:21)
```
[nodejs.org/docs](https://nodejs.org/docs/latest-v20.x/api/perf_hooks.html#performancenodeentrykind)
As far as I understand – JS PerformanceEntry.kind [moved to](https://github.com/nodejs/node/pull/37136/files#diff-f013314c1d6d6722caefc08cbe06ebd18098c40dc1e91230d2a0128d728fea57R338) PerformanceEntry.details.kind

**Comment by Olexandrio** [comment]
I see on github it is already fixed. But npmjs.com has old sources - I looked at it when written issue
